#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    ,               sensorGyro)
#pragma config(Sensor, dgtl3,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl11, rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           rubberband,    tmotorVex393HighSpeed_HBridge, openLoop)
#pragma config(Motor,  port2,           Motor1,        tmotorVex393HighSpeed_MC29, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port3,           Motor2,        tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           Motor3,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           Motor4,        tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           Motor5,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           rightBack,     tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           leftBack,      tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           Intake,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port10,          Intake2,       tmotorVex393HighSpeed_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void shoot(int speed)
{
	motor[Motor1]=speed;
	motor[Motor2]=speed;
	motor[Motor3]=speed;
	motor[Motor4]=speed;
	motor[Motor5]=speed;
}

task main()
{
	while(true)
	{
					motor[leftBack] = vexRT(Ch3);
					motor[rightBack] = vexRT(Ch2);

        // Different speeds set by buttons
        if( vexRT[ Btn6D ] == 1 )
            shoot(60);
        if( vexRT[ Btn6U ] == 1 )
            shoot(90);
        if( vexRT[ Btn5U ] == 1 )
            shoot(120);
        else
            shoot(0);

          if (vexRT[Btn7U] == true)
					{
						motor[Intake] = 120;
						motor[Intake2] = 120;
						motor[rubberband] = 120;
					}
						else if(vexRT[Btn7D] == true)
					{
						motor[Intake] = -120;
						motor[Intake2] = -120;
						motor[rubberband] = -120;
				  }
				  	else if(vexRT[Btn8U] == true)
					{
						motor[Intake] = 50;
						motor[Intake2] = 50;
						motor[rubberband] = 50;
				  }
				  	else if(vexRT[Btn8D] == true)
					{
						motor[Intake] = -50;
						motor[Intake2] = -50;
						motor[rubberband] = -50;
				  }
			      else
					{
						motor[Intake] = 0;
						motor[Intake2] = 0;
						motor[rubberband] = 0;
					}
	}
}
