#pragma config(Sensor, in1,    gyro,           sensorGyro)
#pragma config(Sensor, in5,    potentiometer,  sensorPotentiometer)
#pragma config(Sensor, dgtl1,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  lift_rightEncoder, sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  lift_leftEncoder, sensorQuadEncoder)
#pragma config(Motor,  port1,           hang_1,        tmotorVex393HighSpeed_HBridge, openLoop)
#pragma config(Motor,  port2,           chassis_lf,    tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           chassis_lr,    tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           chassis_rf,    tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           chassis_rr,    tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           lift_1,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           lift_2,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           lift_3,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           lift_4,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port10,          hang_2,        tmotorVex393HighSpeed_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


#define 				rEncoder 								SensorValue[rightEncoder]
#define 				lEncoder 								SensorValue[leftEncoder]
#define 				lrEncoder 							SensorValue[lift_rightEncoder]
#define 				llEncoder 							SensorValue[lift_leftEncoder]
#define 				gyroscope 							SensorValue[gyro]
#define 				anglecheck 							SensorValue[potentiometer]

bool 						encoder_r 				=			false;
bool 						encoder_l 				= 		false;
bool 						lift_encoder_r 		= 		false;
bool 						lift_encoder_l 		=	 		false;
bool 						S_gyro 						= 		false;
bool 						S_potentiometer 	=	 		false;


void lift(int speed){
	motor[lift_1] = speed;
	motor[lift_2] = speed;
	motor[lift_3] = speed;
	motor[lift_4] = speed;
}

task activeSensors(){
	clearTimer(T1);
	do {
		motor[chassis_lf] = 50;
		motor[chassis_rf] = 50;
		motor[chassis_lr] = 100;
		motor[chassis_rr] = 100;
		lift(80);
	}while(time1[T1] < 1000);

	encoder_l = lEncoder >= 20 || lEncoder < 0 ? true : false;
	encoder_r = rEncoder >= 20 || rEncoder < 0 ? true : false;
	lift_encoder_l = lrEncoder >= 50 || lrEncoder < 0 ? true : false;
	lift_encoder_r = llEncoder >= 50 || llEncoder < 0 ? true : false;
	S_gyro = gyroscope >= 5 || gyroscope < 0 ? true : false;
	S_potentiometer = anglecheck >= 5 || anglecheck < 0 ? true : false;

}
