#pragma config(Sensor, in1,    gyro,           sensorGyro)
#pragma config(Sensor, dgtl5,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl1,  right_liftEncoder, sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  left_liftEncoder, sensorQuadEncoder)
#pragma config(Motor,  port1,           lift_5,        tmotorVex393HighSpeed_HBridge, openLoop)
#pragma config(Motor,  port2,           lift_1,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           lift_2,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           chassis_rf,    tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           chassis_rr,    tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           chassis_lf,    tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           chassis_lr,    tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           lift_3,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           lift_4,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port10,          lift_6,        tmotorVex393HighSpeed_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


#define r_Encoder SensorValue[rightEncoder]
#define l_Encoder SensorValue[leftEncoder]
#define ll_Encoder SensorValue[right_liftEncoder]
#define lr_Encoder SensorValue[left_liftEncoder]
#define gyroscope SensorValue[gyro]

const short leftButton = 1;
const short centerButton = 2;
const short rightButton = 4;


void lift(int speed) {
	motor[lift_1] = -speed;
	motor[lift_2] = -speed;
	motor[lift_3] = -speed;
 	motor[lift_4] = -speed;
 	motor[lift_5] = -speed;
  motor[lift_6] = -speed;
}

void push_star(int speed, int encoder_count){
	while(abs(lr_Encoder) < encoder_count){
		lift(speed);
	}
	while(abs(lr_Encoder) > encoder_count){
		lift(-(speed-20));
	}
}

void fence_star(int speed, int encoder_count){
	while(abs(lr_Encoder) < encoder_count){
		lift(speed);
	}
	while(abs(lr_Encoder) > encoder_count){
		lift(-(speed-20));
	}
}



//Wait for Press--------------------------------------------------
void waitForPress()
{
	while(nLCDButtons == 0){}
	wait1Msec(5);
}
//----------------------------------------------------------------

//Wait for Release------------------------------------------------
void waitForRelease()
{
	while(nLCDButtons != 0){}
	wait1Msec(5);
}
//----------------------------------------------------------------

task single_man(){
		r_Encoder = 0;
		l_Encoder = 0;
		ll_Encoder = 0;
		lr_Encoder = 0;
		wait1Msec(250);
		string mainBattery, backupBattery;
    while(1 == 1){



        /*----------------------------------------------------------------/
        /                    Set chassis speed and buttons.               /
        /                    Reverse chassis when Btn6U                   /
        /*---------------------------------------------------------------*/
        motor[chassis_lf] = vexRT[Btn6U] == true ? -vexRT(Ch2) : vexRT(Ch3);
        motor[chassis_lr] = vexRT[Btn6U] == true ? -vexRT(Ch2) : vexRT(Ch3);
        motor[chassis_rf] = vexRT[Btn6U] == true ? -vexRT(Ch3) : vexRT(Ch2);
        motor[chassis_rr] = vexRT[Btn6U] == true ? -vexRT(Ch3) : vexRT(Ch2);

        if(vexRT[Btn5U] == true){
            lift(125);
        }
        else if(vexRT[Btn5D] == true){
            lift(-125);
        }
        else if(vexRT[Btn7U] == true){
            lift(50);
        }
        else if(vexRT[Btn7D] == true){
            lift(-50);
        }
        else if(vexRT[Btn8D] == true){
            fence_star(100, 370);
        }
        else{
            lift(0);
        }

    clearLCDLine(0);											// Clear line 1 (0) of the LCD
		clearLCDLine(1);											// Clear line 2 (1) of the LCD

		//Display the Primary Robot battery voltage
		displayLCDString(0, 0, "Primary: ");
		sprintf(mainBattery, "%1.2f%c", nImmediateBatteryLevel/1000.0,'V'); //Build the value to be displayed
		displayNextLCDString(mainBattery);

		//Display the Backup battery voltage
		displayLCDString(1, 0, "Backup: ");
		sprintf(backupBattery, "%1.2f%c", BackupBatteryLevel/1000.0, 'V');	//Build the value to be displayed
		displayNextLCDString(backupBattery);

		//Short delay for the LCD refresh rate
		wait1Msec(100);

    }
}

task double_man(){
		r_Encoder = 0;
		l_Encoder = 0;
		ll_Encoder = 0;
		lr_Encoder = 0;
		wait1Msec(250);
		string mainBattery, backupBattery;
    while(1 == 1){


        /*----------------------------------------------------------------/
        /                    Set chassis speed and buttons.               /
        /                    Reverse chassis when Btn6U                   /
        /*---------------------------------------------------------------*/
        motor[chassis_lf] = vexRT[Btn6U] == true ? -vexRT(Ch2) : vexRT(Ch3);
        motor[chassis_lr] = vexRT[Btn6U] == true ? -vexRT(Ch2) : vexRT(Ch3);
        motor[chassis_rf] = vexRT[Btn6U] == true ? -vexRT(Ch3) : vexRT(Ch2);
        motor[chassis_rr] = vexRT[Btn6U] == true ? -vexRT(Ch3) : vexRT(Ch2);

        if(vexRT[Btn5UXmtr2] == true){
            lift(125);
        }
        else if(vexRT[Btn5DXmtr2] == true){
            lift(-125);
        }
        else if(vexRT[Btn7UXmtr2] == true){
            lift(50);
        }
        else if(vexRT[Btn7DXmtr2] == true){
            lift(-50);
        }
        else if(vexRT[Btn8DXmtr2] == true){
            fence_star(100, 370);
        }
        else{
            lift(0);
        }

    clearLCDLine(0);											// Clear line 1 (0) of the LCD
		clearLCDLine(1);											// Clear line 2 (1) of the LCD

		//Display the Primary Robot battery voltage
		displayLCDString(0, 0, "Primary: ");
		sprintf(mainBattery, "%1.2f%c", nImmediateBatteryLevel/1000.0,'V'); //Build the value to be displayed
		displayNextLCDString(mainBattery);

		//Display the Backup battery voltage
		displayLCDString(1, 0, "Backup: ");
		sprintf(backupBattery, "%1.2f%c", BackupBatteryLevel/1000.0, 'V');	//Build the value to be displayed
		displayNextLCDString(backupBattery);

		//Short delay for the LCD refresh rate
		wait1Msec(100);

    }
}

task main()
{
	//Declare count variable to keep track of our choice
	int count = 0;

	//------------- Beginning of User Interface Code ---------------
	//Clear LCD
	clearLCDLine(0);
	clearLCDLine(1);
	//Loop while center button is not pressed
	bLCDBacklight = true;
	while(nLCDButtons != centerButton)
	{
		//Switch case that allows the user to choose from 4 different options
		switch(count){
		case 0:
			//Display first choice
			displayLCDCenteredString(0, "Double Man");
			displayLCDCenteredString(1, "<		 Enter		>");
			waitForPress();
			//Increment or decrement "count" based on button press
			if(nLCDButtons == leftButton)
			{
				waitForRelease();
				count = 3;
			}
			else if(nLCDButtons == rightButton)
			{
				waitForRelease();
				count++;
			}
			break;
		case 1:
			//Display second choice
			displayLCDCenteredString(0, "Single Man");
			displayLCDCenteredString(1, "<		 Enter		>");
			waitForPress();
			//Increment or decrement "count" based on button press
			if(nLCDButtons == leftButton)
			{
				waitForRelease();
				count--;
			}
			else if(nLCDButtons == rightButton)
			{
				waitForRelease();
				count = 0;
			}
			break;
		default:
			count = 0;
			break;
		}
	}
	//------------- End of User Interface Code ---------------------

	//------------- Beginning of Robot Movement Code ---------------
	//Clear LCD
	clearLCDLine(0);
	clearLCDLine(1);
	//Switch Case that actually runs the user choice
	bLCDBacklight = true;
	string mainBattery, backupBattery;
	switch(count){
	case 0:
		//If count = 0, run the code correspoinding with choice 1
		displayLCDCenteredString(0, "Double man");
		displayLCDCenteredString(1, "is running!");
		wait1Msec(2000);						// Robot waits for 2000 milliseconds


		// Move forward at full power for 3 seconds
		startTask(double_man);
		break;
	case 1:
		//If count = 1, run the code correspoinding with choice 2
		displayLCDCenteredString(0, "Single Man");
		displayLCDCenteredString(1, "is running!");
		wait1Msec(2000);						// Robot waits for 2000 milliseconds

		// Move reverse at full power for 3 seconds
		startTask(single_man);
		break;
	default:
				//If count = 0, run the code correspoinding with choice 1
		displayLCDCenteredString(0, "Double man");
		displayLCDCenteredString(1, "is running!");
		wait1Msec(2000);						// Robot waits for 2000 milliseconds


		// Move forward at full power for 3 seconds
		startTask(double_man);
		break;
	}

	//------------- End of Robot Movement Code -----------------------
}
