#pragma config(Sensor, in8,    gyro,           sensorGyro)
#pragma config(Sensor, dgtl1,  right_liftEncoder, sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  left_liftEncoder, sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl9,  data,           sensorDigitalOut)
#pragma config(Motor,  port1,           lift_5,        tmotorVex393HighSpeed_HBridge, openLoop)
#pragma config(Motor,  port2,           lift_1,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           lift_2,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           chassis_rf,    tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           chassis_rr,    tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           chassis_lf,    tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           chassis_lr,    tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           lift_3,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           lift_4,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port10,          lift_6,        tmotorVex393HighSpeed_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"
#include "led.c"
#include "Lcd code chooser.c"


/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/
/* The purpose of this program is pick up the cube and hit
four stars off the fence(middle sector)
*/
#define r_Encoder SensorValue[rightEncoder]
#define l_Encoder SensorValue[leftEncoder]
#define ll_Encoder SensorValue[right_liftEncoder]
#define lr_Encoder SensorValue[left_liftEncoder]
#define gyroscope SensorValue[gyro]




void lift(int speed) {
  motor[lift_1] = -speed;
    motor[lift_2] = -speed;
    motor[lift_3] = -speed;
    motor[lift_4] = -speed;
    motor[lift_5] = -speed;
  motor[lift_6] = -speed;
}


void left_drive(int speed){
    motor[chassis_lf] = speed;
    motor[chassis_lr] = speed;
}

void right_drive(int speed){
    motor[chassis_rf] = speed;
    motor[chassis_rr] = speed;
}

void turn(int degrees10){
    while(abs(gyroscope) < degrees10 - 100)
      {
        //...Continue turning
        right_drive(-50);
        left_drive(50);
      }
      //Brief brake to eliminate some drift
      right_drive(5);
      left_drive(-5);
      wait1Msec(100);

      //Second while loop to move more slowly toward the goal
      while(abs(SensorValue[in8]) != degrees10)
      {
        if(abs(SensorValue[in8]) > degrees10)
        {
          right_drive(30);
          left_drive(-30);
        }
        else
        {
          right_drive(-30);
          left_drive(30);
        }
      }
      //Stop
      right_drive(0);
      left_drive(0);
      wait1Msec(250);
}

void move_straight(int speed, int encoder_count){
    while(l_Encoder < encoder_count){
        if(abs(l_Encoder) == abs(r_Encoder)){
            right_drive(speed);
            left_drive(speed);
        }
        else if(abs(l_Encoder) < abs(r_Encoder)){
            right_drive(speed-5);
            left_drive(speed);
        }else{
            right_drive(speed);
            left_drive(speed-5);
        }
      }
     left_drive(0);
     right_drive(0);
     wait1Msec(250);
}

void lift_shoot(int speed, int encoder_count){
    while(l_Encoder > encoder_count){
        if(abs(l_Encoder) == abs(r_Encoder)){
            right_drive(-speed);
            left_drive(-speed);
        }
        else if(abs(l_Encoder) < abs(r_Encoder)){
            right_drive(-(speed-5));
            left_drive(-speed);
        }else{
            right_drive(-speed);
            left_drive(-(speed-5));
        }

        if(l_Encoder > (encoder_count)){
            lift(80);
        }
        else{
            lift(0);
        }
      }
     left_drive(0);
     right_drive(0);
     lift(0);
     wait1Msec(250);
}

void encoder_lift(int speed, int encoder_count){
    while(abs(lr_Encoder) < encoder_count){
        lift(speed);
    }
    /*while(abs(lr_Encoder) > encoder_count){
        lift(-(speed-20));
    }*/
    lift(0);
    wait1Msec(250);
}

void up_down(int speed){
	lift(speed);
	wait1Msec(500);
	lift(-(speed));
	wait1Msec(500);
	lift(0);
	wait1Msec(500);
}
void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;
  startTask(code_chooser);
	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
//Completely clear out any previous sensor readings by setting the port to "sensorNone"
  SensorType[in8] = sensorNone;
  wait1Msec(100);
  //Reconfigure Analog Port 8 as a Gyro sensor and allow time for ROBOTC to calibrate it
  SensorType[in8] = sensorGyro;
  wait1Msec(100);

  r_Encoder = 0;
  l_Encoder = 0;
  ll_Encoder = 0;
  lr_Encoder = 0;
  wait1Msec(100);


  	//------------- Beginning of Robot Movement Code ---------------
	//Clear LCD
	clearLCDLine(0);
	clearLCDLine(1);
	//Switch Case that actually runs the user choice
	switch(count){
	case 0:
		//If count = 0, run the code correspoinding with choice 1
		displayLCDCenteredString(0, "Cube auto(Left)");
		displayLCDCenteredString(1, "is running!");
		wait1Msec(200);						// Robot waits for 200 milliseconds
//encoder_lift(80,250);
  	//lift(50);
		//wait1Msec(200);
  	//up_down(100);

    lift(70);
    wait1Msec(200);
    lift(-100);
    wait1Msec(400);
    lift(-7);
   wait1Msec(100);
    move_straight(60, 550);
    wait1Msec(100);
    encoder_lift(80,190);

    //wait1Msec(1000);
    lift(10);
    wait10Msec(50);

    turn(1250);
    r_Encoder = 0;
    l_Encoder = 0;
    wait1Msec(250);

    //move_straight(80, 180);

    r_Encoder = 0;
    l_Encoder = 0;
    wait1Msec(0);

    lift_shoot(80,-380);
    wait1Msec(250);
    lift(0);
    wait1Msec(500);
		break;
	case 1:
		//If count = 1, run the code correspoinding with choice 2
		displayLCDCenteredString(0, "Stars Defensive");
		displayLCDCenteredString(1, "is running!");
		wait1Msec(200);						// Robot waits for 200 milliseconds

  	lift(70);
		wait1Msec(100);
    lift(-70);
    wait1Msec(250);
    lift(0);
    wait1Msec(100);

    encoder_lift(80, 350);
    wait1Msec(500);
    move_straight(100, 550);
		break;
	default:
		displayLCDCenteredString(0, "No valid choice");
		displayLCDCenteredString(1, "was made!");
		break;
	}
	//------------- End of Robot Movement Code -----------------------

}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/


task usercontrol()
{
 r_Encoder = 0;
        l_Encoder = 0;
        ll_Encoder = 0;
        lr_Encoder = 0;
        wait1Msec(250);
        //startTask(make_sound);
        //startTask(led_lights);

    while(1 == 1){

        /*----------------------------------------------------------------/
        /                    Set chassis speed and buttons.               /
        /                    Reverse chassis when Btn6U                   /
        /*---------------------------------------------------------------*/



        motor[chassis_lf] = vexRT[Btn6U] == true ? -vexRT(Ch2) : vexRT(Ch3);
        motor[chassis_lr] = vexRT[Btn6U] == true ? -vexRT(Ch2) : vexRT(Ch3);
        motor[chassis_rf] = vexRT[Btn6U] == true ? -vexRT(Ch3) : vexRT(Ch2);
        motor[chassis_rr] = vexRT[Btn6U] == true ? -vexRT(Ch3) : vexRT(Ch2);

        if(vexRT[Btn5UXmtr2] == true){
            lift(125);
        }else if(vexRT[Btn5DXmtr2] == true){
            lift(-125);
        }else if(vexRT[Btn6UXmtr2] == true){
        		lift(80);
        }else if(vexRT[Btn7UXmtr2] == true){
            lift(50);
        }else if(vexRT[Btn7DXmtr2] == true){
            lift(-50);
      	//}else if(vexRT[Btn8DXmtr2] == true){
      			//liftPreset(-60);
        }else{
            lift(0);
        }



        wait1Msec(25);
    }
}
