#pragma config(Sensor, in1,    gyro,           sensorGyro)
#pragma config(Sensor, in5,    potentiometer,  sensorPotentiometer)
#pragma config(Sensor, dgtl1,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  lift_rightEncoder, sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  lift_leftEncoder, sensorQuadEncoder)
#pragma config(Motor,  port1,           hang_1,        tmotorVex393HighSpeed_HBridge, openLoop)
#pragma config(Motor,  port2,           chassis_lf,    tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           chassis_lr,    tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           chassis_rf,    tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           chassis_rr,    tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           lift_1,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           lift_2,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           lift_3,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           lift_4,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port10,          hang_2,        tmotorVex393HighSpeed_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "active sensors check.c"

/* lift speed
void lift(int speed){
	motor[lift_1] = speed;
	motor[lift_2] = speed;
	motor[lift_3] = speed;
	motor[lift_4] = speed;
	motor[hang_1] = speed;
	motor[hang_2] = speed;
}*/

task main()
{
	startTask(activeSensors);

	wait1Msec(1000);
	stopTask(activeSensors);

	while(1 == 1){

		/*----------------------------------------------------------------/
		/									Set chassis speed and buttons. 									/
		/ 								Reverse chassis when Btn6U											/
		/*---------------------------------------------------------------*/
		motor[chassis_lf] = vexRT[Btn6U] == true ? -vexRT(Ch3) : vexRT(Ch3);
		motor[chassis_lr] = vexRT[Btn6U] == true ? -vexRT(Ch3) : vexRT(Ch3);
		motor[chassis_rf] = vexRT[Btn6U] == true ? -vexRT(Ch2) : vexRT(Ch2);
		motor[chassis_rr] = vexRT[Btn6U] == true ? -vexRT(Ch2) : vexRT(Ch2);

		if(vexRT[Btn5U] == true){
			lift(127);
		}
		else if(vexRT[Btn5D] == true){
			lift(-127);
		}
		else{
			lift(0);
		}
	}
}
