#pragma config(Sensor, in8,    gyro,           sensorGyro)
#pragma config(Sensor, dgtl5,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl1,  right_liftEncoder, sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  left_liftEncoder, sensorQuadEncoder)
#pragma config(Motor,  port1,           lift_5,        tmotorVex393HighSpeed_HBridge, openLoop)
#pragma config(Motor,  port2,           lift_1,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           lift_2,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           chassis_rf,    tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           chassis_rr,    tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           chassis_lf,    tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           chassis_lr,    tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           lift_3,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           lift_4,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port10,          lift_6,        tmotorVex393HighSpeed_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


#define r_Encoder SensorValue[rightEncoder]
#define l_Encoder SensorValue[leftEncoder]
#define ll_Encoder SensorValue[right_liftEncoder]
#define lr_Encoder SensorValue[left_liftEncoder]
#define gyroscope SensorValue[gyro]

int count;

void lift(int speed) {
  motor[lift_1] = -speed;
    motor[lift_2] = -speed;
    motor[lift_3] = -speed;
    motor[lift_4] = -speed;
    motor[lift_5] = -speed;
  motor[lift_6] = -speed;
}


void left_drive(int speed){
    motor[chassis_lf] = speed;
    motor[chassis_lr] = speed;
}

void right_drive(int speed){
    motor[chassis_rf] = speed;
    motor[chassis_rr] = speed;
}

void turn(int degrees10){
    while(abs(gyroscope) < degrees10 - 100)
      {
        //...Continue turning
        right_drive(-50);
        left_drive(50);
      }
      //Brief brake to eliminate some drift
      right_drive(5);
      left_drive(-5);
      wait1Msec(100);

      //Second while loop to move more slowly toward the goal
      while(abs(SensorValue[in8]) != degrees10)
      {
        if(abs(SensorValue[in8]) > degrees10)
        {
          right_drive(30);
          left_drive(-30);
        }
        else
        {
          right_drive(-30);
          left_drive(30);
        }
      }
      //Stop
      right_drive(0);
      left_drive(0);
      wait1Msec(250);
}

void move_straight(int speed, int encoder_count){
    while(l_Encoder < encoder_count){
        if((l_Encoder) == (r_Encoder)){
            right_drive(speed);
            left_drive(speed);
        }
        else if((l_Encoder) < (r_Encoder)){
            right_drive(speed-8);
            left_drive(speed);
        }else{
            right_drive(speed);
            left_drive(speed-8);
        }
      }
     left_drive(0);
     right_drive(0);
     wait1Msec(250);
}

void lift_shoot(int speed, int encoder_count){
    while(l_Encoder > encoder_count){
        if((l_Encoder) == (r_Encoder)){
            right_drive(-speed);
            left_drive(-speed);
        }else if((l_Encoder) < (r_Encoder)){
            right_drive(-(speed-20));
            left_drive(-speed);
        }else{
            right_drive(-speed);
            left_drive(-(speed-20));
        }

        if(l_Encoder > (encoder_count) && lr_Encoder < 600){
            lift(120);
        }else{
            lift(0);
        }
      }
     left_drive(0);
     right_drive(0);
     lift(0);
     wait1Msec(250);
}
void move_back(int speed, int encoder_count){
	while(l_Encoder > encoder_count){
			if((l_Encoder) == (r_Encoder)){
	      right_drive(-speed);
	      left_drive(-speed);
	    }else if((l_Encoder) < (r_Encoder)){
	      right_drive(-(speed-5));
	      left_drive(-speed);
	    }else{
	      right_drive(-speed);
	      left_drive(-(speed-5));
	  	}
		}
}
void move_back2(int speed, int encoder_count){
	while(l_Encoder > encoder_count){
			if((l_Encoder) == (r_Encoder)){
	      right_drive(-speed);
	      left_drive(-speed);
	    }else if((l_Encoder) < (r_Encoder)){
	      right_drive(-(speed-5));
	      left_drive(-speed);
	    }else{
	      right_drive(-speed);
	      left_drive(-(speed-5));
	  	}
		}
	left_drive(0);
  right_drive(0);
  wait1Msec(250);
}

void encoder_lift(int speed, int encoder_count){
    while(abs(lr_Encoder) < encoder_count){
        lift(speed);
    }
    /*while(abs(lr_Encoder) > encoder_count){
        lift(-(speed-20));
    }*/
    lift(0);
    wait1Msec(250);
}
void lift_down(int speed, int encoder_count){
	while((lr_Encoder) > encoder_count){
        lift(-(speed));
    }
    lift(0);
    wait1Msec(250);
}

void preloads(int runs){
	while(count <= runs){
		encoder_lift(80, 300);
  	move_back(80, -100);
  	lift_shoot(120, -500);
	}
	lift(0);
	right_drive(0);
	left_drive(0);
	wait1Msec(250);
}

void stop_chassis(int time){
	left_drive(0);
	right_drive(0);
	wait1Msec(time);
}

void intake_flipout(){
	move_back2(80, -15);
	lift_down(100, -5);
  stop_chassis(100);
}

task main()
{
	//Completely clear out any previous sensor readings by setting the port to "sensorNone"
  SensorType[in8] = sensorNone;
  wait1Msec(500);
  //Reconfigure Analog Port 8 as a Gyro sensor and allow time for ROBOTC to calibrate it
  SensorType[in8] = sensorGyro;
  wait1Msec(500);

  r_Encoder = 0;
  l_Encoder = 0;
  ll_Encoder = 0;
  lr_Encoder = 0;
  wait1Msec(250);

  clearTimer(T1);
  while(time1[T1] < 1000000){

  	intake_flipout();

  	encoder_lift(80, 150);
  	wait1Msec(500);


  	move_back(80, -300);
  	lift_shoot(100, -600);
  	wait1Msec(500);
  	lift_down(80, 0);
  	move_straight(80, -350);
  	/*encoder_lift(80, 300);
  	move_back(80, -250);
  	lift_shoot(100, -600);

  	lift_down(80, 250);
  	wait1Msec(500);
  	move_straight(80, -150);
  	encoder_lift(80, 250);
  	move_back(80, -250);
  	lift_shoot(100, -500);

  	/*lift_down(80, 300);
  	move_straight(80, 0);
  	move_back(80, -100);
  	lift_shoot(120, -500);*/
  	break;
  }
}
