#pragma config(Sensor, in1,    gyro,           sensorGyro)
#pragma config(Sensor, dgtl5,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl1,  right_liftEncoder, sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  left_liftEncoder, sensorQuadEncoder)
#pragma config(Motor,  port1,           lift_5,        tmotorVex393HighSpeed_HBridge, openLoop)
#pragma config(Motor,  port2,           lift_1,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           lift_2,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           chassis_rf,    tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           chassis_rr,    tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           chassis_lf,    tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           chassis_lr,    tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           lift_3,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           lift_4,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port10,          lift_6,        tmotorVex393HighSpeed_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


#define r_Encoder SensorValue[rightEncoder]
#define l_Encoder SensorValue[leftEncoder]
#define ll_Encoder SensorValue[right_liftEncoder]
#define lr_Encoder SensorValue[left_liftEncoder]
#define gyroscope SensorValue[gyro]


void lift(int speed) {
  motor[lift_1] = -speed;
  motor[lift_2] = -speed;
  motor[lift_3] = -speed;
  motor[lift_4] = -speed;
  motor[lift_5] = -speed;
  motor[lift_6] = -speed;
}

void push_star(int speed, int encoder_count){
    while(abs(lr_Encoder) < encoder_count){
        lift(speed);
    }
    while(abs(lr_Encoder) > encoder_count){
        lift(-(speed-20));
    }
}

void fence_star(int speed, int encoder_count){
    while(abs(lr_Encoder) < encoder_count){
        lift(speed);
    }
    while(abs(lr_Encoder) > encoder_count){
        lift(-(speed-20));
    }
}

task main()
{
        r_Encoder = 0;
        l_Encoder = 0;
        ll_Encoder = 0;
        lr_Encoder = 0;
        wait1Msec(250);
    while(1 == 1){

        /*----------------------------------------------------------------/
        /                    Set chassis speed and buttons.               /
        /                    Reverse chassis when Btn6U                   /
        /*---------------------------------------------------------------*/
        motor[chassis_lf] = vexRT[Btn6U] == true ? -vexRT(Ch2) : vexRT(Ch3);
        motor[chassis_lr] = vexRT[Btn6U] == true ? -vexRT(Ch2) : vexRT(Ch3);
        motor[chassis_rf] = vexRT[Btn6U] == true ? -vexRT(Ch3) : vexRT(Ch2);
        motor[chassis_rr] = vexRT[Btn6U] == true ? -vexRT(Ch3) : vexRT(Ch2);

        if(vexRT[Btn5UXmtr2] == true){
            lift(125);
        }
        else if(vexRT[Btn5DXmtr2] == true){
            lift(-125);
        }
        else if(vexRT[Btn7UXmtr2] == true){
            lift(50);
        }
        else if(vexRT[Btn7DXmtr2] == true){
            lift(-50);
        }
        else if(vexRT[Btn8DXmtr2] == true){
        	push_star(80, 50);
        }
        else if(vexRT[Btn8UXmtr2] == true){
        	fence_star(80, 370);
        }
        else{
            lift(0);
        }

    }
}
