#pragma config(Motor,  port10,          h_intake,      tmotorVex393TurboSpeed_HBridge, openLoop)
#pragma config(Motor,  port2,           d_left,        tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           y_right,       tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           sL1,           tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           sR1,           tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           sR,            tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           sL,            tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           y_left,        tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           d_right,       tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port1,           v_intake,      tmotorVex393TurboSpeed_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//



void shoot(int speed)
{
	motor[sL1]=speed;
	motor[sL]=speed;
	motor[sR1]=speed;
	motor[sR]=speed;
}

task main()
{
	while(true)
	{
		motor[d_left]=vexRT(Ch3);
		motor[d_right]=vexRT(Ch2);
		motor[y_left]=vexRT(Ch3);
		motor[y_right]=vexRT(Ch2);

		if(vexRT[Btn5DXmtr2] == true)
		{
			shoot(0);
		}
		if(vexRT[Btn5UXmtr2] == true)
		{
			shoot(80);
		}
		if(vexRT[Btn6DXmtr2] == true)
		{
			shoot(65);
		}
		if(vexRT[Btn6UXmtr2] == true)
		{
			shoot(125);
		}


		if(vexRT[Btn7UXmtr2] == true)
		{
			motor[h_intake] = 127;
		}
		else if(vexRT[Btn7DXmtr2] == true)
		{
			motor[h_intake] = -127;
		}
		else
		{
			motor[h_intake] = 0;
		}



		if(vexRT[Btn8UXmtr2] == true)
		{
			motor[v_intake] = 127;
		}
		else if(vexRT[Btn8DXmtr2] == true)
		{
			motor[v_intake] = -127;
		}
		else
		{
			motor[v_intake] = 0;
		}


	}
}
